Moovee_2/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Moovee_2.Models;
using Moovee_2.Repositories;
using System.Data;
using System;
using System.Linq;

namespace Moovee_2.Controllers
{
    public class MovieController : Controller
    {
		private readonly MovieRepository _movieRepository;
		public MovieController(MovieRepository movieRepository)
		{
			_movieRepository = movieRepository;
		}


		public ViewResult Index(string searchString)
		{
			var movies = _movieRepository.GetList();
			if (!String.IsNullOrEmpty(searchString))
			{
				movies = movies.Where(s => s.Title.ToLower().Contains(searchString.ToLower())
				|| s.Genre.ToLower().Contains(searchString.ToLower())
				|| s.MainActress.ToLower().Contains(searchString.ToLower())).ToList();
			}

			return View(movies);
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Create(Movie movie)
		{
			_movieRepository.Create(movie);
			return RedirectToAction(nameof(Index));
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Update(int id)
		{
			var movie = _movieRepository.GetById(id);
			return View(movie);
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Update(Movie movie)
		{
			_movieRepository.Update(movie);
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Details(int id)
		{
			var result = _movieRepository.GetById(id);
			return View(result);
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Delete(int id)
		{
			var tvShow = _movieRepository.GetById(id);
			return View(tvShow);
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Delete(Movie movie)
		{
			_movieRepository.Delete(movie);
			return RedirectToAction(nameof(Index));
		}
	}
}

Moovee_2/Controllers/TvShowController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Moovee_2.Models;
using Moovee_2.Repositories;
using System;
using System.Data;
using System.Linq;

namespace Moovee_2.Controllers
{
    public class TvShowController : Controller
    {
		private readonly TvShowRepository _tvShowRepository;
		public TvShowController (TvShowRepository tvShowRepository)
		{
			_tvShowRepository = tvShowRepository;
		}


		public ViewResult Index(string searchString)
		{
			var tvShows = _tvShowRepository.GetList();
			if (!String.IsNullOrEmpty(searchString))
			{
				tvShows = tvShows.Where(s => s.Title.ToLower().Contains(searchString.ToLower())
				|| s.Genre.ToLower().Contains(searchString.ToLower())
				|| s.MainActress.ToLower().Contains(searchString.ToLower())).ToList();
			}

			return View(tvShows);
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Create(TvShow tvShow)
		{
			_tvShowRepository.Create(tvShow);
			return RedirectToAction(nameof(Index));
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Update(int id)
		{
			var tvShow = _tvShowRepository.GetById(id);
			return View(tvShow);
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Update(TvShow tvShow)
		{
			_tvShowRepository.Update(tvShow);
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Details(int id)
		{
			var result = _tvShowRepository.GetById(id);
			return View(result);
		}

		[Authorize(Roles = "Admin")]
		[HttpGet]
		public IActionResult Delete(int id)
		{
			var tvShow = _tvShowRepository.GetById(id);
			return View(tvShow);
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult Delete(TvShow tvShow)
		{
			_tvShowRepository.Delete(tvShow);
			return RedirectToAction(nameof(Index));
		}
	}
}

Moovee_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Moovee Database Forum</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<style>
		/* .navbar {
					position: fixed;
					top: 0;
					width: 100%;
				}*/
	</style>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-light bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/logo/Mooveee_header.png" alt="header_logo" width="200" height="64" /></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-0">
						<li class="nav-item">
							@using (Html.BeginForm())
							{
								<div>
									Filter by name:
									@Html.TextBox("SearchString")
									@*<input type="submit" value="GO!" />*@
								</div>
							}
						</li>
					</ul>
					<ul class="navbar-nav flex-grow-1">
						@*<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="TvShow" asp-action="Index">Tv Shows</a>
						</li>


@*						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" href="#">Action</a>
								<a class="dropdown-item" href="#">Another action</a>
								<a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>*@


					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container" style="color:purple">
			&copy; 2023 - Mooveee Database Forum - <a href="#">Don't click</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>